### ISSUE TITLE
Can't install Lua Language Server (unzip is not executable)

### ISSUE THREAD

**Issue by tannerellen** [williamboman/mason-lspconfig.nvim#10]
### Problem description

When trying to install the lua-language-server either from the Mason UI or using :LspInstall sumneko_lua the server install fails with a message in Mason that says "spawn: unzip failed with exit code - and signal -. unzip is not executable"

<img width="1141" alt="Screen Shot 2022-07-25 at 11 02 41 PM" src="https://user-images.githubusercontent.com/930897/180934608-74b8dc33-bcf1-4a99-9c94-d642145d8f5f.png">
.

### Why do you think this is an issue with mason-lspconfig.nvim?

This may be an issue with Mason and not mason-lspconfig but the installation process is a lsp server. Lua seems like an important language server to work correctly.

### Neovim version (>= 0.7)

NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 20

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

lua-language-server

### Steps to reproduce

1. Use the command :LspInstall sumneko_lua

### Actual behavior

Language server doesn't install and there is an error reported in :Mason

### Expected behavior

Language server should install

### LspInfo

```Text
Configured servers list: tsserver, html, cssls, sumneko_lua, svelte
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - OK: **PHP**: `PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )`
  - OK: **npm**: `8.11.0`
  - OK: **node**: `v16.15.1`
  - OK: **python3**: `Python 3.8.10`
  - WARNING: **pip3**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.20.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.30`
  - OK: **bash**: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 7. Remaining: 53. Limit: 60. Reset: Tue 26 Jul 2022 06:38:24 AM UTC.
```

**Comment by tannerellen** [comment]
Sorry didn't troubleshoot this enough. I installed unzip with sudo apt install unzip and everything works great now. I read the message to mean that unzip couldn't unzip the file not that unzip wasn't installed at all.

Issue is resolved.

**Comment by mvillasante** [comment]
> Sorry didn't troubleshoot this enough. I installed unzip with sudo apt install unzip and everything works great now. I read the message to mean that unzip couldn't unzip the file not that unzip wasn't installed at all.
> 
> Issue is resolved.

It helps me a lot. 
Thanks
