### ISSUE TITLE
include the full mapping table between mason server names and lspconfig server names in the documentation

### ISSUE THREAD

**Issue by jam1015** [williamboman/mason-lspconfig.nvim#106]
### Is your feature request related to a problem? Please describe.

there is a link to the table translating the server names mason <--> lspconfig, but what if we are working without a gui? best to include the table in the documentaiton itself with a warning that it could  be outdated.

### Describe the solution you'd like

include the table in the documentation.  sorry I don't know how to do a pull request or I would!

### Describe potential alternatives you've considered

crosrefferencing the LspInstall commands and what comes up in MasonInfo after installing to infer the server names

**Comment by williamboman** [comment]
Makes sense, added in #107 available via `:h mason-lspconfig-server-map`
