### ISSUE TITLE
Automatically install all servers that are loaded by lspconfig

### ISSUE THREAD

**Issue by SingularisArt** [williamboman/mason-lspconfig.nvim#111]
### Is your feature request related to a problem? Please describe.

I'm not exactly sure if this feature is already available, but I've got the following servers:

```lua
servers = {
  "bashls",
  "clangd",
  "cssls",
  "cssmodules_ls",
  "tailwindcss",
  "emmet_ls",
  "html",
  "golangci_lint_ls",
  "jdtls",
  "jsonls",
  "pyright",
  "rust_analyzer",
  "solang",
  "solc",
  "solidity_ls",
  "sqls",
  "texlab",
  "tsserver",
  "sumneko_lua",
  "yamlls",
}
```

Instead of manually having to write out all the servers `mason-lspconfig.nvim` should install, is it possible to have it install all the servers that are loaded by `lspconfig` itself?

For example, `mason-null-ls.nvim` uses the table passed to `null-ls`. Can you see if you can add this feature, if, again, it doesn't already exist?

**Comment by williamboman** [comment]
Hello have you seen `automatic_installation`? Setting it to `true` will make `mason-lspconfig` pick up which servers are set up via lspconfig and install these (you can exclude specific servers from auto installations as well)
