### ISSUE TITLE
Is there a way to `ensure_installed` non-LSPs?

### ISSUE THREAD

**Issue by hahuang65** [williamboman/mason-lspconfig.nvim#113]
If I wanted to automatically install DAP, Linters, and Formatters?
Listing them in the `ensure_installed` won't work.

**Comment by zsmatrix62** [comment]
Need to ensure install formatters.

**Comment by hahuang65** [comment]
> Need to ensure install formatters.

That's not a feature yet is it?

**Comment by nshen** [comment]
you can try this https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim

**Comment by hahuang65** [comment]
@nshen this is perfect, thank you!

**Comment by maxmx03** [comment]
> > you can try this https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim
> 
> It will be great if no plugin is required. The last update time of the linked project is in January. @hahuang65 Maybe it would be great to keep this issue open.

Well this is my solution for the moment.

```lua
vim.api.nvim_create_autocmd('VimEnter', {
  pattern = '*',
  callback = function()
    local masonpath = vim.fn.stdpath 'data' .. '/mason/bin/'

    for _, format in pairs(ide.formattings) do
      if not vim.loop.fs_access(masonpath .. format, 'X') then
        if type(format) == 'string' then
          vim.cmd('MasonInstall ' .. format)
        else
          vim.cmd('MasonInstall ' .. format.name)
        end
      end
    end
  end,
})
```

**Comment by williamboman** [comment]
@maxmx03 You probably want to use Mason's [Lua API](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) instead, something like so:

```lua
local registry = require("mason-registry")

for _, pkg_name in ipairs { "stylua", "prettier" } do
  local ok, pkg = pcall(registry.get_package, pkg_name)
  if ok then
    if not pkg:is_installed() then
       pkg:install()
    end
  end
end
```

**Comment by williamboman** [comment]
> Then I will go for this method instead. I tried the linked plugin and I have to use names like `ltex-ls` there, which causes issues like this: #168.

I'm not sure I'm following. `ensure_installed` in `mason-lspconfig.nvim` uses nvim-lspconfig server names whereas `mason-tool-installer` uses `mason.nvim` package names. If you use `mason-tool-installer` you don't really have any reason to also use the `ensure_installed` feature in `mason-lspconfig.nvim`.

> Does it check for updates btw?

Nope but you can customize it further with [`pkg:check_new_version()`](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md#packagecheck_new_versioncallback) (`mason-tool-installer` does this already)

**Comment by jc00ke** [comment]
> `ensure_installed` in `mason-lspconfig.nvim` uses nvim-lspconfig server names whereas `mason-tool-installer` uses `mason.nvim` package names.

Sorry for commenting on a closed issue, but I found your comment and it seems to conflict with the names in `nvim-lspconfig`, namely the [bashls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#bashls) server per the screenshot below.

![image](https://user-images.githubusercontent.com/18191/226472487-de050482-fa77-42be-bb85-5b2e70c41c79.png)

Can you provide a link to the correct LSP server names? :pray: 

Thank you!

**Comment by williamboman** [comment]
@jc00ke https://github.com/williamboman/mason.nvim/issues/1045#issuecomment-1454013966

**Comment by jc00ke** [comment]
@williamboman yep, that was it. I now remember either you telling me that or figuring it out, and then I went and fixed it on a branch... only to be totally and utterly forgotten :rofl: 

I had all sorts of stuff wrong, which I mostly fixed in https://github.com/jc00ke/dotfiles/commit/4db691365cfbbe0f88c3d8417c1af253e412522d
