### ISSUE TITLE
Implement LSP server naming inside Mason Installer window

### ISSUE THREAD

**Issue by TheRealLorenz** [williamboman/mason-lspconfig.nvim#116]
### Is your feature request related to a problem? Please describe.

I found it unconvenient to have to lookup the table for the naming conversion between lsp and mason on the README when I have to configure a new server.

### Describe the solution you'd like

I think would be useful to add a field inside every entry of the Mason Installer which could display the lsp server name of the server.

For instance, the server `json-lsp` would have the field `jsonls`.

Obviously for those who don't use lspconfig this shouldn't be the case; that's why I think it could be a sort of injection made by this plugin.

**Comment by williamboman** [comment]
Hello! This is exactly something I actually had a feature branch for some time ago. After an accidental `rm -rf` I lost it and never revisited. I'll revisit it again!

**Comment by avegancafe** [comment]
@TheRealLorenz if you update to the latest `main` you should be all set. The lspconfig name for each package is now shown next to the entry
