### ISSUE TITLE
[Maybe it's more a question than a request] Does the ensure_installed also ensures the servers are updated?

### ISSUE THREAD

**Issue by kassio** [williamboman/mason-lspconfig.nvim#12]
### Is your feature request related to a problem? Please describe.

I really like to live in the edge, so I update my nvim plugins, local environment daily. What's the easiest way to do that with mason?

### Describe the solution you'd like

Ideally, `ensure_installed` would also ensure the servers are updated. But, I also envision a `ensure_updated` as a possible solution.

**Comment by dagadbm** [comment]
https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim

**Comment by williamboman** [comment]
Hello! No it doesn't. The `ensure_installed` and `automatic_installation` settings in this plugin are remnants of the same settings in nvim-lsp-installer. I decided to keep them to make migration easier. As @dagadbm linked, there exists a 3rd party plugin that provides auto-install and auto-update capabilities. Also see https://github.com/williamboman/mason.nvim/issues/103 for more details!

**Comment by kassio** [comment]
That's great! Thanks @williamboman and @dagadbm
