### ISSUE TITLE
Intelephense (PHP) having trouble with `licenceKey` setting

### ISSUE THREAD

**Issue by cprn** [williamboman/mason-lspconfig.nvim#129]
### Problem description

Installing Intelephense (langserver for PHP) and using its basic functionality works fine but  it has a premium **Goto Implementation** function that requires passing a license key to the server. When I try to use it I get error saying there's no provider for goto implementation method even though my license key is correct.

Intelephense logs are in neither `:MasonLog` nor `:LspLog`, don't know how to get to them. I'm using [nvim-lua/kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim). I'm setting up a `licenceKey` property with correct value in `init.lua` according to Mason schema.

I assume person taking care of the integration has a working license key. If not - I can share for debugging purposes.

### Why do you think this is an issue with mason-lspconfig.nvim?

It works fine with [neoclide/coc.nvim](https://github.com/neoclide/coc.nvim) set in `~/coc-settings.json`:

```json
{
    "intelephense.licenceKey": "key goes here"
}
```

I made sure I'm using the same key in both cases. I tried to put a key in a `text/plain` file as well and paste in the path to the file in place of `licenceKey` - same result - works in CoC, doesn't work with Mason LSP config.

Pasting an incorrect license key prints Intelephense error message in `:CocInfo`.

### Neovim version (>= 0.7)

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux blackshit 6.0.15-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Dec 21 21:14:38 UTC 2022 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

Intelephense

### Steps to reproduce

On clean `nvim`:
1. install [nvim-lua/kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) (it includes Mason and all that's required)
1. in `init.lua` add `intelephense` with correct settings schema (`intelephense.licenceKey`) in `servers` variable like so:
```lua
local servers = {
    -- [...]
    intelephense = {     -- server name
        intelephense = { -- settings schema starts here
            licenceKey = 'key goes here',
        },
    },
}
```
3. save, Mason will automatically install the server without issues
1. quit
1. open a PHP project using interfaces
1. find any interface and press `gI` (capital i) sequence

### Actual behavior

Error message:
```
method textDocument/implementation is not supported by any of the servers registered for the current buffer
```

### Expected behavior

Opening a list of available interface implementations.

### LspInfo

```Text
Use [q] or [Esc] to quit the window
 
 Language client log: /home/cg/.local/state/nvim/lsp.log
 Detected filetype:   php
 
 1 client(s) attached to this buffer: 
 
 Client: intelephense (id: 1, bufnr: [1, 11])
 	filetypes:       php
 	autostart:       true
 	root directory:  /home/cg/Projects/work/IPSP/Banker/Banker4
 	cmd:             intelephense --stdio
 
 Configured servers list: intelephense, ltex, pylsp, bashls, grammarly, pyright, r_language_server, clangd, sourcery, tsserver, sumneko_lua, sqlls
```

### LspLog

```Text
[START][2023-01-16 01:35:34] LSP logging initiated
[WARN][2023-01-16 01:35:34] .../lua/vim/lsp.lua:96	"method textDocument/implementation is not supported by any of the servers registered for the current buffer"
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]`
  - OK: **RubyGem**: `3.3.25`
  - OK: **Composer**: `Composer version 2.5.1 2022-12-22 15:33:54`
  - OK: **PHP**: `PHP 8.1.13 (cli) (built: Dec 12 2022 23:45:33) (NTS)`
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v19.3.0`
  - OK: **python3**: `Python 3.10.8`
  - OK: **pip3**: `pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 19.0.1`
  - OK: **java**: `java version "19.0.1" 2022-10-18`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **JAVA_HOME**: `java version "19.0.1" 2022-10-18`
  - OK: GitHub API rate limit. Used: 3. Remaining: 57. Limit: 60. Reset: Mon, 16 Jan 2023, 02:12:21.
```

**Comment by ronald2wing** [comment]
https://intelephense.com/faq.html

If you are unable or unwilling to provide the key via the above option then you can place your licence key in a text file at:

YOUR_HOME_DIR/intelephense/licence.txt

Where YOUR_HOME_DIR is:

POSIX: Will use the $HOME environment variable if defined. Otherwise, it will use the effective UID to look up the user's home directory.

Windows: Will use the USERPROFILE environment variable if defined. Otherwise it will be the path to the profile directory of the current user.

**Comment by cprn** [comment]
Thanks, this works as a workaround - I didn't know about default license path. Shouldn't it work through a settings schema, though? Am I passing it wrong? I tried to ommit one level of `intelephense` in the `servers` object as well even though I know it's not what schema says, so this:

```lua
local servers = {
    -- [...]
    intelephense = { -- server name
        licenceKey = 'key goes here', -- schema starts here now
    },
}
```

instead of this:

```lua
local servers = {
    -- [...]
    intelephense = {     -- server name
        intelephense = { -- settings schema starts here
            licenceKey = 'key goes here',
        },
    },
}
```

The value of `servers[server_name]` is passed as `settings` a little bit lower in the setup handler like so:

```lua
mason_lspconfig.setup {
    ensure_installed = vim.tbl_keys(servers),
}

mason_lspconfig.setup_handlers {
    function(server_name)
        require('lspconfig')[server_name].setup {
            capabilities = capabilities,
            on_attach = on_attach,
            settings = servers[server_name],
        }
    end,
}
```

**Comment by ronald2wing** [comment]
Add init_options to the table in the require('lspconfig')[server_name].setup()

configs.init_options = { licenceKey = vim.env.INTELEPHENSE_LICENCE_KEY }

The other method is cleaner with Neovim LSP's current setup.

**Comment by cprn** [comment]
So you're saying it's a bug in [nvim-lua/kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim)? Instead of `settings = servers[server_name]` it should be this (below)? I'm confused because it doesn't seem to work and `sumneko_lua` server that comes preconfigured works fine with passing Manson provided schema in `settings` property.

```lua
mason_lspconfig.setup_handlers {
    function(server_name)
        require('lspconfig')[server_name].setup {
            capabilities = capabilities,
            on_attach = on_attach,
            configs = { init_options = servers[server_name] },
        }
    end,
}
```

**Comment by ronald2wing** [comment]
Add init_options only when the server is intelephense.
`mason_lspconfig.setup_handlers {
    function(server_name)
        require('lspconfig')[server_name].setup {
            capabilities = capabilities,
            on_attach = on_attach,
            init_options = { licenceKey = 'You Key Here' }
        }
    end,
}`

**Comment by cprn** [comment]
Oh, OK. I'm still confused though about what is an expected behavior. Is the settings schema provided by Mason for Intelephense wrong or should this be handled in [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) or is it something with this specific language server and [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim) and it *should* with `intelephense.licenceKey` passed through `settings` property but for some reason doesn't?

Mason provides schema like so:
![image](https://user-images.githubusercontent.com/6132708/212592419-267886b9-2d84-4373-8777-3a26d80002c5.png)

And on this list there's `→ intelephense.licenceKey` so I'm passing it in the handler like so:
```lua
settings = { intelephense = { licenceKey = 'key goes here' } },
```
and it doesn't work. You say it's supposed to be passed like this - and I checked it works:
```lua
init_options = { licenceKey = 'key goes here' } },
```

But there's another server that comes preconfigured and Mason shows schema like `→ Lua.workspace.checkThirdParty` and passing it in settings like so works fine:

```lua
settings = { Lua = { workspace = { checkThirdParty = false } } },
```

So my guess is that schema is wrong and should be fixed and that there's a separate issue of `init_options` that isn't handled separately in [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) like so:

```lua
local servers = {
    -- [...]
    intelephense = {
        settings = { -- settings according to schema
            intelephense = { foo = bar },
        }, 
        init_options = { -- severs specific flags
            licenceKey = 'key goes here',
        },
    },
}

-- [...]

mason_lspconfig.setup_handlers {
    function(server_name)
        require('lspconfig')[server_name].setup {
            capabilities = capabilities,
            on_attach = on_attach,
            settings = servers[server_name][settings],
            init_options = servers[server_name][init_options],
        }
    end,
}
```

**Comment by ronald2wing** [comment]
That's why I gave you a simpler way to add the license. A better feature to add these settings for each LSP server would be good.

**Comment by williamboman** [comment]
Hey! So the settings schemas displayed in the Mason window is most of the time sourced from the JSON schema of a VSCode extension. These VSCode extensions often accept additional settings that don't relate at all to the underlying LSP server, and they may process these settings before passing them through to the LSP server. In the case of Intelephense, they [extract the licenceKey setting and provide it in the `initializationOptions` object](https://github.com/bmewburn/vscode-intelephense/blob/0e13a1fd28e129c56c6d908e71180495985be601/src/extension.ts#L143-L149), so the suggested solution above is valid.

Ideally, LSP server developers would decouple the server implementation from the VSCode extension, and provide a separate JSON schema for the LSP server itself. Unfortunately this is rarely done. I've decided to still display these setting schemas, when available, because I believe they're net positive and help with discoverability. 

I'm also of the opinion that LSP server implementations should not make use of `initializationOptions` or `workspace/configuration` to collect user settings, but instead rely on editor-agnostic, standardized, configuration files. But that's besides the point 😄

**Comment by KaspervdHeijden** [comment]
For all googlers. This is a working setup:

```lua
require('mason').setup(opts)
require('mason-lspconfig').setup()

local servers = {
    html   = { filetypes = { 'html', 'twig', 'hbs'} },
    lua_ls = {
        -- ...
    },
    intelephense = {
        init_options = {
            globalStoragePath = os.getenv('HOME') .. '/.local/share/intelephense',
            licenceKey        = os.getenv('NVIM_INTELEPHENSE_LICENCEKEY'), -- Or wherever you get it from
        },
    },
}

local capabilities    = require('cmp_nvim_lsp').default_capabilities(vim.lsp.protocol.make_client_capabilities())
local mason_lspconfig = require 'mason-lspconfig'

mason_lspconfig.setup({ ensure_installed = vim.tbl_keys(servers) })
mason_lspconfig.setup_handlers({
    function (server_name)
        require('lspconfig')[server_name].setup({
            init_options = (servers[server_name] or {}).init_options,
            filetypes    = (servers[server_name] or {}).filetypes,
            settings     = servers[server_name],
            capabilities = capabilities,
            on_attach    = on_attach,
        })
    end,
})
```

**Comment by codemonkey76** [comment]
> For all googlers. This is a working setup:
> 
> ```lua
> require('mason').setup(opts)
> require('mason-lspconfig').setup()
> 
> local servers = {
>     html   = { filetypes = { 'html', 'twig', 'hbs'} },
>     lua_ls = {
>         -- ...
>     },
>     intelephense = {
>         init_options = {
>             globalStoragePath = os.getenv('HOME') .. '/.local/share/intelephense',
>             licenceKey        = os.getenv('NVIM_INTELEPHENSE_LICENCEKEY'), -- Or wherever you get it from
>         },
>     },
> }
> 
> local capabilities    = require('cmp_nvim_lsp').default_capabilities(vim.lsp.protocol.make_client_capabilities())
> local mason_lspconfig = require 'mason-lspconfig'
> 
> mason_lspconfig.setup({ ensure_installed = vim.tbl_keys(servers) })
> mason_lspconfig.setup_handlers({
>     function (server_name)
>         require('lspconfig')[server_name].setup({
>             init_options = (servers[server_name] or {}).init_options,
>             filetypes    = (servers[server_name] or {}).filetypes,
>             settings     = servers[server_name],
>             capabilities = capabilities,
>             on_attach    = on_attach,
>         })
>     end,
> })
> ```

How do you check whether the license key was successfully retrieved and passed to intelephense, i used this and still getting codeActions not available
