### ISSUE TITLE
Sumneko changed name to LuaLS

### ISSUE THREAD

**Issue by notjl** [williamboman/mason-lspconfig.nvim#147]
### Problem description

nvim-lspconfig merged a PR to notify users of the deprecation of `sumneko_lua`, they encourage to use `lua_ls` instead

### Why do you think this is an issue with mason-lspconfig.nvim?

mason.nvim has `lua-language-server` instead of `sumneko_lua`.

### Neovim version (>= 0.7)

NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux FLLFFL 6.1.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 18 Jan 2023 19:54:38 +0000 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

sumneko_lua

### Steps to reproduce

1. Install latest nvim-lspconfig, mason-lspconfig.nvim, mason.nvim, junnplus/lsp-setup.nvim commit
2. Install `sumneko_lua` under `servers`
3. Open any `.lua` file

### Actual behavior

Receive an error:
```
sumneko_lua is deprecated, use lua_ls instead. See :h deprecated
This function will be removed in lspconfig version 0.2.0
```

### Expected behavior

No errors, warnings of deprecation.

### LspInfo

```Text
Language client log: /home/tako/.local/state/nvim/lsp.log
 Detected filetype:   lua
 
 1 client(s) attached to this buffer: 
 
 Client: lua_ls (id: 1, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/tako/Repositories/tuldok/nvim/.config/nvim/lua/
 	cmd:             lua-language-server
 
 Configured servers list: lua_ls, pylsp
```

### LspLog

```Text
None. No error stating sumneko_lua being the problem.
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.66.1`
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]`
  - OK: **RubyGem**: `3.3.25`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - ERROR: **npm**: not available
  - OK: **node**: `v19.5.0`
  - OK: **python3**: `Python 3.10.9`
  - OK: **pip3**: `pip 22.3.1 from /home/tako/.local/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Sunday, 12 February, 2023 12:55:38 PM.
```

### Screenshots or recordings

![image](https://user-images.githubusercontent.com/58279268/218292212-dfd0d99d-4dbb-4b89-a67a-a197c685de70.png)

**Comment by nyngwang** [comment]
What should we do now to suppress the error message?
