### ISSUE TITLE
no more `on_server_ready` helper func?

### ISSUE THREAD

**Issue by marcosnils** [williamboman/mason-lspconfig.nvim#15]
### Is your feature request related to a problem? Please describe.

Yes, with `nvim-lsp-installer` I liked the fact that I could do `LspInstall` and after the lsp was installed, it was automatically configured and registered by nvim-lsp-installer without having to actually modify any `.lua` files to do the setup. 

Now, I have to manually call `lspconfig.<lsp>.setup` for each of the LSP's that I want to use.

### Describe the solution you'd like

Have a helper function so mason-lspconfig registers installed tools automatically

**Comment by marcosnils** [comment]
nvm.. just found it in the doc.

**Comment by sirupsen** [comment]
I think an addition to the README on how to use `on_attach` with `mason-lspconfig.nvim` would really help though! @williamboman

**Comment by williamboman** [comment]
> I think an addition to the README on how to use `on_attach` with `mason-lspconfig.nvim` would really help though! 🙏🏻 @williamboman

Yeah no I agree, I just really like vim help files and wish more plugins made use of them haha. By `on_attach`, do you mean the general interaction with `lspconfig`? By default, mason (and mason-lspconfig) tries to get out of the way as much as possible, so as long as you've set up both plugins (2 lines), you can interact with lspconfig as you would normally.

```lua
require("mason").setup()
require("mason-lspconfig").setup()

require("lspconfig").sumneko_lua.setup {}
require("lspconfig").rust_analyzer.setup {}
```

Then, there are some additional convenience APIs that can automate this setup for you. Maybe I should include example snippets for all of these approaches?

**Comment by sirupsen** [comment]
By the way, LOVE your work :) Even more that you upped the ambition even more from your original project to mason. Hero!

Personally I confront the README for all setup instructions, and then the help files generally later... I don't know how common that is, but I doubt not super uncommon. I think it's kind of in the spirit of `mason-lspconfig` to automatically call `setup` on all of the installed ones, or at least easily be able to do that? If you want to customize it, then call it _again_ with custom options? Or is that crazy?

**Comment by jaredmcqueen** [comment]
+1 for automatically attach installed LSP servers.  The `LspInstall` / `MasonInstall` convenience factor is killed when having to manually add each and every server. 

Maybe a sane default would be to automatically attach all servers, with an option to disable?

**Comment by mbacalan** [comment]
> > I think an addition to the README on how to use `on_attach` with `mason-lspconfig.nvim` would really help though! 🙏🏻 @williamboman
> 
> Yeah no I agree, I just really like vim help files and wish more plugins made use of them haha. By `on_attach`, do you mean the general interaction with `lspconfig`? By default, mason (and mason-lspconfig) tries to get out of the way as much as possible, so as long as you've set up both plugins (2 lines), you can interact with lspconfig as you would normally.
> 
> ```lua
> require("mason").setup()
> require("mason-lspconfig").setup()
> 
> require("lspconfig").sumneko_lua.setup {}
> require("lspconfig").rust_analyzer.setup {}
> ```
> 
> Then, there are some additional convenience APIs that can automate this setup for you. Maybe I should include example snippets for all of these approaches?

This would be really nice IMO. I personally moved to mason from lsp-installer and wasn't sure if I needed to change anything in the way I'm configuring my language servers or not, as there isn't much information available about it here.
