### ISSUE TITLE
Support for rustywind lsp for sorting tailwind classes

### ISSUE THREAD

**Issue by collegeimprovements** [williamboman/mason-lspconfig.nvim#154]
### Is your feature request related to a problem? Please describe.

Currently we need to install `rustywind` via `Mason`.
If we can support `rustywind` in `mason-lspconfig.nvim`'s config then we can add it to `ensure_installed` block.

### Describe the solution you'd like

Supporting `rustywind` lsp so that we can add it to `ensure_installed` block.

### Describe potential alternatives you've considered

Manually installing `rustywind` via Mason.

**Comment by williamboman** [comment]
Hey! Rustywind is not a language server, so it's not in scope for mason-lspconfig.
