### ISSUE TITLE
Add CCLS to list of servers

### ISSUE THREAD

**Issue by CalebDW** [williamboman/mason-lspconfig.nvim#155]
### Is your feature request related to a problem? Please describe.

Hello,

Could you please add [ccls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ccls) to the list of servers?

Thanks!

### Describe the solution you'd like

For the LSP to be installable through Mason.

**Comment by williamboman** [comment]
Hey! ccls is not supported by mason.nvim. They only provide amenities for building from source, which has been difficult to support in the past (slow installations, poor cross-platform support, many support issues). There are some more capable package managers out there that provide ccls binaries, it's recommended to use them to install it (or build manually from source).
