### ISSUE TITLE
Can't install any ruby lsp with Mason

### ISSUE THREAD

**Issue by vkuppoor** [williamboman/mason-lspconfig.nvim#156]
Hey, I'm experiencing the same issue raised before. I'm using the up to date version of Mason, but I can't install any of the Ruby LSPs like solargraph. I posted below an image of what's in the directory produced by the :MasonInstall --debug solargraph command.
[mason-solargraph-issue.pdf](https://github.com/williamboman/mason-lspconfig.nvim/files/10775379/mason-solargraph-issue.pdf)
![Image 2-18-23 at 6 26 PM](https://user-images.githubusercontent.com/49379423/219904227-d67921cc-59d2-469a-9ac5-e4d595d6616d.jpg)

_Originally posted by @vkuppoor in https://github.com/williamboman/mason-lspconfig.nvim/issues/94#issuecomment-1435792541_

**Comment by williamboman** [comment]
Hey! Could you file this using the issue template available in https://github.com/williamboman/mason.nvim?
