### ISSUE TITLE
Is it a new bug?

### ISSUE THREAD

**Issue by MonadeInFlask** [williamboman/mason-lspconfig.nvim#160]
![screen](https://user-images.githubusercontent.com/19179479/221238202-6dd9c423-d7fa-4388-9ab4-aa20985c2cb0.jpg)
These names are right  before.

**Comment by tannerellen** [comment]
I was running into this as well and did some troubleshooting and was able to fix this by removing the dependency properties I had in my plugin config for lazy. I believe I was using dependency improperly in lazy.nvim because I migrated from packer and used it in a similar way. Once I removed all my dependency references related to mason and lspconfig this error went away.

**Comment by williamboman** [comment]
Hello! You're probably setting up mason.nvim too late (i.e. you're setting up mason-lspconfig.nvim before mason.nvim).

**Comment by MonadeInFlask** [comment]
> Hello! You're probably setting up mason.nvim too late (i.e. you're setting up mason-lspconfig.nvim before mason.nvim). If you're using a package manager to load plugins for you, you need to make sure it loads things in the right order.

Thank you. My problem has been solved with your method.

**Comment by zer09** [comment]
I got similar issue after changing sumneko_lua  to lua_ls and I am seeing warning like this
```[lspconfig] Cannot access configuration for lua_ls. Ensure this server is listed in `server_configurations.md` or added as a custom server.```

And here is my config
```lua
return {
	{
		"williamboman/mason.nvim",
		cmd = "Mason",
		keys = {
			{
				"<Leader>cm",
				"<cmd>Mason<cr>",
				desc = "Mason",
			},
		},
		config = function()
			require("mason").setup({
				ui = {
					icons = {
						package_installed = "✓",
						package_pending = "➜",
						package_uninstalled = "✗",
					},
				},
			})
		end,
	},
	{
		"neovim/nvim-lspconfig",
		dependencies = {
			"mason.nvim",
			"williamboman/mason-lspconfig.nvim",
			"jose-elias-alvarez/typescript.nvim",
			"hrsh7th/cmp-nvim-lsp",
		},
		config = function()
			local lspconfig = require("lspconfig")
			local mason_lsp_config = require("mason-lspconfig")

			local capabilities =
				require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities())
			capabilities.textDocument.completion.completionItem.snippetSupport = true

			local on_attach = function(client, bufnr)
				-- Disabled lsp formatting
				client.server_capabilities.document_formatting = false
				client.server_capabilities.document_range_formatting = false

				require("mappings").lsp_on_attach(bufnr)
			end

			mason_lsp_config.setup({
				ensure_installed = {
					"angularls",
					"bashls",
					"cssls",
					"eslint",
					"gopls",
					"html",
					"jsonls",
					"rust_analyzer",
					"lua_ls",
					"svelte",
					"tailwindcss",
					"tsserver",
					"yamlls",
				},
				automatic_installation = true,
			})

			mason_lsp_config.setup_handlers({
				function(server_name)
					lspconfig[server_name].setup({
						on_attach = on_attach,
						capabilities = capabilities,
					})
				end,
				["jsonls"] = function(_)
					lspconfig.jsonls.setup({
						on_attach = on_attach,
						capabilities = capabilities,
						settings = {
							json = require("schemastore").json.schemas(),
						},
					})
				end,
				["lua_ls"] = function(_)
					lspconfig.lua_ls.setup({
						on_attach = on_attach,
						capabilities = capabilities,
						settings = {
							Lua = {
								diagnostics = {
									globals = { "vim" },
								},
							},
						},
					})
				end,
				["tsserver"] = function(_)
					require("typescript").setup({
						server = {
							on_attach = function(client, bufnr)
								on_attach(client, bufnr)

								if vim.fn.findfile("angular.json", ".;") ~= "" then
									client.server_capabilities.renameProvider = false
								end

								require("mappings").typescript(bufnr)
							end,
							capabilities = capabilities,
						},
					})
				end,
			})
		end,
	},
}

```

**Comment by williamboman** [comment]
I'm sorry I can't help with how to set it up using lazy.nvim as I don't have any experience with it

**Comment by williamboman** [comment]
I don't believe Packer loads plugins in the order they're defined. If you delegate loading to Packer you'll have to explicitly instruct it (through directives like `after`). I personally leverage the builtin `:h 'plugin'` mechanism, in which case it's loaded alphabetically based on filename (i.e. `plugin/Mason.lua` executes before `plugin/lspconfig.lua`).

**Comment by syntaxman** [comment]
@piersolenski   I have an almost identical setup that suddenly started throwing those errors.  Rather than using "after", I used ` requires = {'...'}, `
