### ISSUE TITLE
Cannot install `gopls`, `delve`: `cgo: C compiler "x86_64-conda-linux-gun-cc" not found: exec [...] file not found in $PATH`.

### ISSUE THREAD

**Issue by nyngwang** [williamboman/mason-lspconfig.nvim#191]
### Problem description

Cannot install go-related packages like `gopls`, `delve`.

<img src="https://user-images.githubusercontent.com/24765272/231789441-04765c55-c9e0-444a-ba97-9d446d6dc28c.png" width="600">
<img src="https://user-images.githubusercontent.com/24765272/231789917-8e1c55ad-4b79-4f8e-8230-2aa3b5716ef6.png" width="600">

### Why do you think this is an issue with mason-lspconfig.nvim?

error message reported by `[mason-lspconfig]`

### Neovim version (>= 0.7)

NVIM v0.10.0-dev-57+gb85ac8932
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux pochita 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

gopls, delve

### Steps to reproduce

1. Create a conda virtual environment and install `go=1.18`
2. Open neovim and try to install gopls&delve by pressing `i` on `gopls`/`delve` on mason's interface.

### Actual behavior

<img src="https://user-images.githubusercontent.com/24765272/231787533-e37190a0-fc1a-4831-9b3c-698c703832d3.png" width="600">

### Expected behavior

install without error

### LspInfo

```Text
Configured servers list: cmake, pyright, bashls, dockerls, lua_ls, vimls, clangd
```

### LspLog

```Text
it's empty
```

### Healthcheck

```Text
mason: require("mason.health").check()

    mason.nvim report
    - OK neovim version >= 0.7.0
    - OK Registry require("mason-registry.index") is installed.
    - OK Registry github.com/mason-org/mason-registry version: 2023-04-13-agreed-ermine is installed.
    - OK **unzip**: UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
    - OK **Go**: go version go1.18.5 linux/amd64
    - WARNING **cargo**: not available
    - WARNING **luarocks**: not available
    - WARNING **Ruby**: not available
    - WARNING **RubyGem**: not available
    - WARNING **Composer**: not available
    - WARNING **PHP**: not available
    - OK **npm**: 9.5.0
    - OK **node**: v18.15.0
    - OK **python3**: Python 3.11.3
    - OK **pip3**: pip 23.0.1 from /home/me/miniforge3/envs/main/lib/python3.11/site-packages/pip (python 3.11)
    - WARNING **javac**: not available
    - OK **java**: openjdk version "11.0.18" 2023-01-17
    - WARNING **julia**: not available
    - OK **wget**: GNU Wget 1.21.2 built on linux-gnu.
    - OK **curl**: curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.
    2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
    - OK **gzip**: gzip 1.10
    - OK **tar**: tar (GNU tar) 1.34
    - WARNING **pwsh**: not available
    - OK **bash**: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
    - OK **sh**: Ok
    - OK **python3_host_prog**: Python 3.11.3
    - OK **python3_host_prog pip**: pip 23.0.1 from /home/me/miniforge3/envs/main/lib/python3.11/site-packages/pip (python 3.11)
    - OK GitHub API rate limit. Used: 9. Remaining: 51. Limit: 60. Reset: Thu 13 Apr 2023 10:56:10 PM CST.
```

**Comment by williamboman** [comment]
Hello! You seem to be missing the C compiler. I'd recommend you refer to the go docs (and perhaps Conda) to figure out what's wrong.
