### ISSUE TITLE
Add support for ccls

### ISSUE THREAD

**Issue by james2432** [williamboman/mason-lspconfig.nvim#219]
### Is your feature request related to a problem? Please describe.

ccls is an lsp with faster indexing and can support gcc as the backend.

https://github.com/MaskRay/ccls

### Describe the solution you'd like

Add ccls as supported lsp

**Comment by williamboman** [comment]
Hello! See https://github.com/williamboman/mason.nvim/issues/349#issuecomment-1230136092
