### ISSUE TITLE
setup_handlers gives error on startup

### ISSUE THREAD

**Issue by huboles** [williamboman/mason-lspconfig.nvim#223]
Ever since installing version 1.4.0, whenever I open nvim I get this error:
```
Error detected while processing /home/huck/.config/nvim/init.lua:
Vim:E1174: String required for argument 1
Press ENTER or type command to continue
```
There doesn't seem to be any problems, as all of my LSP servers are still setup and loaded, I just have to skip through this error every time I open a new instance of nvim.

I've traced the error to this function in a file called by my init.lua:
```
local handlers = {
    function(server_name)
        require('lspconfig')[server_name].setup({})
    end,
}

require('mason-lspconfig').setup_handlers(handlers)
```

I haven't made any changes to my config since upgrading, so something seems to have changed within mason-lspconfig

I can still setup LSP servers manually using `require('lspconfig')[LSP_SERVER].setup({})`, but would prefer to use the automatic setup rather than listing out all of the languages I use.

**Comment by postfen** [comment]
Thanks for tracing this down. I'm also receiving the same error with the same lines. When removed, the error goes away.

**Comment by williamboman** [comment]
This is an issue with nvim-lspconfig, they recently made some changes. I'd try updating nvim-lspconfig and see if it's resolved, otherwise it's best to file an issue there.
