### ISSUE TITLE
E5248: Invalid character in group name (omnisharp)

### ISSUE THREAD

**Issue by Izanagi-96** [williamboman/mason-lspconfig.nvim#241]
### Problem description

When ever I try to edit in cs file this error will popup not letting me work at all

### Why do you think this is an issue with mason-lspconfig.nvim?

Don't what to say I'm pretty sure and I know a lot of people are having the same problem no matter if they are using LunarVim or AstroNvim which is what I use myself and vanilla neovim

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Windows 11

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [ ] Yes

### Affected language servers

omnisharp

### Steps to reproduce

1.Just open any C# project
2.Make some changes

### Actual behavior

infinite errors

### Expected behavior

no errors

### LspInfo

```Text
Detected filetype:   cs
 
 1 client(s) attached to this buffer: 
 
 Client: omnisharp (id: 1, bufnr: [7])
 	filetypes:       cs, vb
 	autostart:       true
 	root directory:  C:/Users/Izanagi/Desktop/CosmicEngine
 	cmd:             C:\Users\Izanagi\AppData\Local\nvim-data\mason\bin\omnisharp.CMD -z -s C:/Users/Izanagi/Desktop/CosmicEngine --hostPID 12056 DotNet:enablePackageRestore=false --encoding utf-8 --languageserver FormattingOptions:EnableEditorConfigSupport=true Sdk:IncludePrereleases=true
```

### LspLog

```Text
yes: "OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService: No symbol found. File: 'path', Line: 34, Column: 0. | "
```

### Healthcheck

```Text
can't see my neovim crashes when I use the checkhealth command
```

**Comment by williamboman** [comment]
#211
