### ISSUE TITLE
inconsistent mappings classifiers: language vs filetype?

### ISSUE THREAD

**Issue by kylo252** [williamboman/mason-lspconfig.nvim#26]
## Background

we got `parse_packages_from_user_args()` checking against a `language` mapping

https://github.com/williamboman/mason-lspconfig.nvim/blob/e95ee7b6c811a4ed734a724b93e59f5181cdfe93/lua/mason-lspconfig/api/command.lua#L18-L21

whereas `parse_packages_from_heuristics()` uses the term `filetype` instead

https://github.com/williamboman/mason-lspconfig.nvim/blob/e95ee7b6c811a4ed734a724b93e59f5181cdfe93/lua/mason-lspconfig/api/command.lua#L52-L55

this makes it harder to track in the documentation

https://github.com/williamboman/mason-lspconfig.nvim/blob/e95ee7b6c811a4ed734a724b93e59f5181cdfe93/doc/mason-lspconfig.txt#L84-L89

### Suggested solution

- It's probably for the best to pick a qualifier and stick with it to avoid confusion, my vote goes for either `filetype` or [`languageId`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem)
- there's no reason that `parse_packages_from_user_args()` should rely on `mason.mappings.language`
- consider renaming `mason.mappings.language` in [mason.nvim](https://github.com/williamboman/mason.nvim)

**Comment by williamboman** [comment]
Hey! These serve different purposes, where the "language" mapping allow convenient installation by explicitly providing a language you want to install (`:LspInstall lua`). From what I've observed, this seems to be a pretty common way for users to install a server. The filetype-backed installation is never directly surfaced to users and is only in place to support the use case where you just run `:LspInstall` and a list of suggested servers are presented to you. This is sourced from the filetype mappings in lspconfig.

As for sourcing from LSPs languageId - I'm not sure the list of languages is part of the spec, and even if they were they'd have to be manually mapped somewhere?

**Comment by kylo252** [comment]
> The filetype-backed installation is never directly surfaced to users and is only in place to support the use case where you just run `:LspInstall` and a list of suggested servers are presented to you. This is sourced from the filetype mappings in lspconfig.

oh I'm not arguing the use-case, it's rather just the wording/terminology. 

compare these two prompts

https://github.com/williamboman/mason-lspconfig.nvim/blob/e95ee7b6c811a4ed734a724b93e59f5181cdfe93/lua/mason-lspconfig/api/command.lua#L30

vs

https://github.com/williamboman/mason-lspconfig.nvim/blob/e95ee7b6c811a4ed734a724b93e59f5181cdfe93/lua/mason-lspconfig/api/command.lua#L58

> As for sourcing from LSPs languageId - I'm not sure the list of languages is part of the spec, and even if they were they'd have to be manually mapped to a lspconfig server, or Mason package, somewhere?

I think they're currently a recommendation, but what I want to get across is that neovim treats `filetype` as `languageId` in nearly all the [cases](https://github.com/neovim/neovim/commit/564dd7d8db110d134987f8619c3894d2149f8956) where it's relevant, and [`language` is just shortened from `languageId`](https://code.visualstudio.com/docs/languages/identifiers) when it's user-facing, at least that's how I interpret it.

---

I'm probably being overly pedantic here, but I figured it's worth pointing out to see if we could arrive at a consistent naming scheme.

**Comment by williamboman** [comment]
Ah ok now I follow. Had there been such a structured enumeration of languages (which also were to have a 1:1 relation with Vim's `'filetype'`) it'd be great, but to my knowledge it doesn't really exist. I also still can't help but view these as separate concepts.

My thinking is as follows:
1) The "languages" are sourced from Mason's language definitions. These are entirely internalized in Mason and are really only meant for UI components, as well as `:LspInstall <language>` where they're lowercased. It's not meant for "programmatic" use, as opposed to `'filetype'`.
1) `'filetype'` has some characteristics that I think makes it a bad identifier for a "language":
    1) There's often multiple filetypes for the same language. Take `typescript`, `typescript.jsx` and `typescriptreact` for example - are these three distinct "languages"?
    1) Although it is the exception, there are 3rd party plugins language plugins that fill in missing ftdetect, leading to "unstandardized" filetypes.
1) I don't think the prompt examples are problematic from a user experience point of view? One is centered around `'filetype'`, which is a very central Vim concept, and the other is for when a user explicitly provides a language. In both cases these are visible in the prompt.
1) The purpose of these things in the context of Mason is purely to enable a better end-user experience. I personally don't really care too much where things are sourced from. If getting rid of one of the underlying mappings is achievable without a worsened experience I'm all for it!
