### ISSUE TITLE
Unable to install ocamllsp

### ISSUE THREAD

**Issue by iawaknahc** [williamboman/mason-lspconfig.nvim#263]
### Problem description

The mapping from `ocamllsp` to `ocaml-lsp` is incorrect. The correct one is from `ocamllsp` to `ocaml-lsp-server`. See https://github.com/ocaml/ocaml-lsp#opam

It can be worked around with

```lua
return {
  {
    'williamboman/mason-lspconfig.nvim',
    dependencies = {
      "williamboman/mason.nvim",
    },
    config = function()
      local mappings = require('mason-lspconfig.mappings.server')
      mappings["ocamllsp"] = "ocaml-lsp-server"

      require('mason-lspconfig').setup {
        automatic_installation = true,
      }
    end,
  },
}
```

### Why do you think this is an issue with mason-lspconfig.nvim?

With the incorrect mapping, it cannot install ocaml-lsp.

### Neovim version (>= 0.7)

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

ocamllsp

### Steps to reproduce

Enable `ocamllsp` and see mason-lspconfig.nvim cannot tell mason.nvim to install `ocaml-lsp-server`

### Actual behavior

Run the command `:MasonLog` and see this error

> [ERROR Thu Aug 10 11:48:40 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=ocaml-lsp) error=spawn: opam failed with exit code 5 and signal 0. 

And see the manpage of opam and find

> EXIT STATUS
> ...
> 5   Not found. You requested something (package, version, repository, etc.) that couldn't be found.
> ...

### Expected behavior

Install `ocaml-lsp-server` correctly

### LspInfo

```Text
non-applicable in this case
```

### Healthcheck

```Text
non-applicable in this case
```

**Comment by williamboman** [comment]
Hello! The mapping is correct (and also validated in CI). The override you provided will also not have any effect because that module provides its mapping via two properties on the module table (not directly on the module table itself). The error you provided suggests opam is failing to install `ocaml-lsp-server`.
