### ISSUE TITLE
Add `nginx-language-server`

### ISSUE THREAD

**Issue by adrian5** [williamboman/mason-lspconfig.nvim#298]
### Is your feature request related to a problem? Please describe.

I don't know if this repo is even the right place to ask, but I wanted to add [nginx-language-server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#nginx_language_server) to my mason-managed LSPs. I followed the same pattern as usual but got this error:

```
[mason-lspconfig.nvim] Server "nginx_language_server" is not a valid entry in ensure_installed. Make sure to only provide lspconfig server names.
```

The mason.nvim registry also lists the server.  I think I might have been lucky so far in that my choices of LSPs were always mainstream enough to be supported.

### Describe the solution you'd like

Would be nice to see this server supported via `ensure_installed`.

**Comment by BBboy01** [comment]
same here...
