### ISSUE TITLE
Add Dart lang support

### ISSUE THREAD

**Issue by grab-a-byte** [williamboman/mason-lspconfig.nvim#328]
### Is your feature request related to a problem? Please describe.

Unable to use dartls in ensure installed servers.

### Describe the solution you'd like

I'd like to have the dart lsp added to this. 
I use kickstart.nvim (which uses this repo) and while the dartls appears to be in the base nvim-lspconfig repo here https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/dartls.lua
However when adding `  dartls={},` to the list of servers in the 'servers' section of the kickstart init file I get the message 
![image](https://github.com/williamboman/mason-lspconfig.nvim/assets/30392071/60117833-809e-420b-b3fe-f5e15b99ad7e)

Not sure if its missing a mapping in here also?

**Comment by williamboman** [comment]
Hello! Please see https://github.com/mason-org/mason-registry/pull/3827#pullrequestreview-1796823736
