### ISSUE TITLE
Add Sourcekit LSP Support

### ISSUE THREAD

**Issue by Blackjacx** [williamboman/mason-lspconfig.nvim#329]
### Is your feature request related to a problem? Please describe.

Unable to use https://github.com/apple/sourcekit-lsp

### Describe the solution you'd like

Liek all the other LSP's please integrate Sourcekit LSP • Swift language

**Comment by johntheocs** [comment]
I need this too. Thanks for consideration.

**Comment by williamboman** [comment]
Hello! Sourcekit comes bundled with the Swift toolchain itself. Packaging it as a standalone package in Mason is not in scope. It also relies on output from other tools in your toolchain, so managing it outside of the toolchain would likely cause a lot of issues.
