### ISSUE TITLE
Omnisharp is shown in LspInfo even it is not configured

### ISSUE THREAD

**Issue by 3699394** [williamboman/mason-lspconfig.nvim#33]
### Problem description

In the commit [https://github.com/williamboman/mason-lspconfig.nvim/commit/3364c6bbddfb5ffdc56a6688ce1865e23cf327d4](url)

`lua/mason-lspconfig/server_config_extensions.lua` is added. And line 4 `configs.omnisharp_mono = require "lspconfig.server_configurations.omnisharp"` is configurating omnisharp_mono for everyone.

### Why do you think this is an issue with mason-lspconfig.nvim?

Prior to this commit, it was working alright.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Linux 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

omnisharp_mono

### Steps to reproduce

1, use the latest commit 3364c6bbddfb5ffdc56a6688ce1865e23cf327d4
2, run `:LspInfo`

### Actual behavior

`:LspInfo` shows omnisharp_mono is configured 

### Expected behavior

`:LspInfo` only shows lsp that is configured by user

### LspInfo

```Text
~                Language client log: /home/abc/.cache/nvim/lsp.log
~                Detected filetype:
~
~                0 client(s) attached to this buffer:
~
~                Configured servers list: tsserver, gopls, sumneko_lua, omnisharp_mono, clangd, rust_analyzer, pyright
```

### Healthcheck

```Text
2 mason: require("mason.health").check()
  3 ========================================================================
  4 ## mason.nvim report
  5   - OK: neovim version >= 0.7.0
  6   - OK: Go: `go version go1.18.2 linux/amd64`
  7   - OK: cargo: `cargo 1.63.0 (fd9c4297c 2022-07-01)`
  8   - WARNING: luarocks: not available
  9   - OK: Ruby: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
 10   - OK: RubyGem: `3.3.5`
 11   - WARNING: Composer: not available
 12   - WARNING: PHP: not available
 13   - OK: npm: `8.11.0`
 14   - OK: node: `v16.16.0`
 15   - OK: python3: `Python 3.10.4`
 16   - OK: pip3: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
 17   - WARNING: javac: not available
 18   - WARNING: java: not available
 19   - WARNING: julia: not available
 20   - OK: wget: `GNU Wget 1.21.2 built on linux-gnu.`
 21   - OK: curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+                libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12`
 22   - OK: gzip: `gzip 1.10`
 23   - OK: tar: `tar (GNU tar) 1.34`
 24   - OK: bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
 25   - OK: sh: `Ok`
 26   - OK: GitHub API rate limit. Used: 15. Remaining: 45. Limit: 60. Reset: Sat Aug 13 23:50:54 2022.
 27
```

**Comment by 3699394** [comment]
Would you mind sharing your thought of creating `lua/mason-lspconfig/server_config_extensions.lua`? So I can create a pr

**Comment by williamboman** [comment]
Hello! So `omnisharp_mono` showing up in `:LspInfo` doesn't necessarily mean that it is configured. That window is provided by `lspconfig`, and it simply checks which keys are present in the configs table.

The reason it was added was to make the Mono variant of omnisharp easier to use via Mason.

I can see it leading to some confusion, will try to submit a patch to `lspconfig` so that only servers that have been set up are displayed

**Comment by datwaft** [comment]
I am also encountering this issue.

I have a custom health module which shows me if every command for every server I have configure is executable, and as you can see it shows `omnisharp_mono`, even if I haven't configured it.

```markdown
conf: require("conf.health").check()
========================================================================
## LSP server executables
  - OK: bashls: the command 'bash-language-server' is executable.
  - OK: clangd: the command 'clangd' is executable.
  - OK: clojure_lsp: the command 'clojure-lsp' is executable.
  - OK: cmake: the command 'cmake-language-server' is executable.
  - OK: cssls: the command 'vscode-css-language-server' is executable.
  - OK: dockerls: the command 'docker-langserver' is executable.
  - OK: emmet_ls: the command 'emmet-ls' is executable.
  - OK: eslint: the command 'vscode-eslint-language-server' is executable.
  - OK: html: the command 'vscode-html-language-server' is executable.
  - OK: jsonls: the command 'vscode-json-language-server' is executable.
  - WARNING: omnisharp_mono: the command is not defined.
  - OK: pyright: the command 'pyright-langserver' is executable.
  - OK: rnix: the command 'rnix-lsp' is executable.
  - OK: rust_analyzer: the command 'rust-analyzer' is executable.
  - OK: sumneko_lua: the command 'lua-language-server' is executable.
  - OK: svelte: the command 'svelteserver' is executable.
  - OK: taplo: the command 'taplo' is executable.
  - OK: tsserver: the command 'typescript-language-server' is executable.
  - OK: vimls: the command 'vim-language-server' is executable.
  - OK: volar: the command 'vue-language-server' is executable.
  - OK: yamlls: the command 'yaml-language-server' is executable.
```

**Comment by williamboman** [comment]
@datwaft Just out of interest, how do you gather which server executables to check?

**Comment by datwaft** [comment]
> @datwaft Just out of interest, how do you gather which server executables to check?

The code is in [here](https://github.com/datwaft/nvim.conf/blob/0c4581b8bec74ec4d215933e61b8c3e43ee8366c/fnl/conf/health.fnl#L23), if you want to see it (it's programmed in Fennel).

Essentially I am using `require("lspconfig").available_servers()`, which returns a list of the servers I have configured. After that I iterate over the list and do `require("lspconfig")[name].cmd[1]`, with name being the name of the LSP server. The `[1]` is used to extract only the executable name and not the parameters to the executable.

Here is an small code snippet:

```lua
local config = require("lspconfig")

local server_list = config.available_servers()

for _, name in ipairs(server_list) do
  local server_configuration = config[name]
  if server_configuration.cmd ~= nil then
    print(server_configuration.cmd[1])
  end
end
```

**Comment by williamboman** [comment]
See https://github.com/neovim/nvim-lspconfig/pull/2066 as a potential solution to this.

**Comment by williamboman** [comment]
Should be fixed upstream now

**Comment by 3699394** [comment]
Not sure if the issue is fixed.
using `NVIM v0.8.0-dev-929-g9a100ee16`  and `b004cc6` of `nvim-lspconfig`, `omnisharp_mono` is still showing in `LspInfo`

**Comment by williamboman** [comment]
`(╯°□°)╯︵ ┻━┻`

**Comment by williamboman** [comment]
Should be fixed upstream in https://github.com/neovim/nvim-lspconfig/pull/2081. I'll close this here as it's not really a Mason issue anyway
