### ISSUE TITLE
Clangd installed by mason doesn't contain c++20 support

### ISSUE THREAD

**Issue by RomaLzhih** [williamboman/mason-lspconfig.nvim#334]
### Problem description

Mason installed clangd contains only the headers for c++ 17, missing headers for c++20, results in the feature usage i.e., `std::ranges` will be reported as error in LSP.

![image](https://github.com/williamboman/mason-lspconfig.nvim/assets/45626759/8dbd0f06-d001-4c8e-87b7-c928ae5b6241)

### Why do you think this is an issue with mason-lspconfig.nvim?

The program compiled without error using system default compiler, while the LSP shows the error. 
I have tried add `.clangd` or `compile_commands.jasn` but it does not work. 

### Neovim version (>= 0.7)

0.8

### Operating system/version

centos 8

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

clangd

### Steps to reproduce

After install clangd. Use some cpp20 features

### Actual behavior

![image](https://github.com/williamboman/mason-lspconfig.nvim/assets/45626759/2af26040-ea81-48d4-a283-e8e85d66e8c7)

![image](https://github.com/williamboman/mason-lspconfig.nvim/assets/45626759/c9620bcc-aa89-4733-b8ae-e7d60544557e)

![image](https://github.com/williamboman/mason-lspconfig.nvim/assets/45626759/e868e475-404c-4b2c-a381-b067363950e6)

### Expected behavior

No error messages.

### LspInfo

```Text
Attached in `Actual behavior` session.
```

### LspLog

```Text
Attached in `Actual behavior` session.
```

### Healthcheck

```Text
Not installed.
```

**Comment by judemille** [comment]
Clangd version 17.x is the latest. Most likely, it's not picking up your `compile_commands.json`. Try adding `--compile-commands-dir=<DIRECTORY CONTAINING JSON>` to the server arguments. Also, make sure that the compile commands contain `-std=c++20`.

**Comment by RomaLzhih** [comment]
Thanks for your suggestion! I tried but it doesn't work :(

I found the issue might be the default version of `clang`, which is 14 in my machine (I compile the programs using `clang17`). After changing it to `gcc`, where the default version is 13, everything works...
