### ISSUE TITLE
not able to configure tsserver

### ISSUE THREAD

**Issue by mslalith** [williamboman/mason-lspconfig.nvim#36]
### Problem description

Whenever a tsserver is opened, typescript-language-server is getting crashed with deepmerge package not found.
I tried installing the package myself but the issue persists

### Why do you think this is an issue with mason-lspconfig.nvim?

This issue is seen after I've migrated to mason. No issues with nvim-lsp-installer

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system/version

Darwin ms-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [x] Yes

### Affected language servers

tsserver

### Steps to reproduce

1. Open a typescript file in neovim

### Actual behavior

typescript-language-server is not being loaded

### Expected behavior

typescript-language-server should be loaded

### LspInfo

```Text
[START][2022-08-22 18:35:21] LSP logging initiated
[ERROR][2022-08-22 18:35:21] .../vim/lsp/rpc.lua:420	"rpc"	"typescript-language-server"	"stderr"	"node:internal/errors:477\n    ErrorCaptureStackTrace(err);\n    ^\n\nError [ERR_MODULE_NOT_FOUND]: Cannot find package 'deepmerge' imported from /Users/mslalith/.local/share/nvim/mason/packages/typescript-language-server/node_modules/typescript-language-server/lib/configuration-manager.js\n    at new NodeError (node:internal/errors:387:5)\n    at packageResolve (node:internal/modules/esm/resolve:909:9)\n    at moduleResolve (node:internal/modules/esm/resolve:958:20)\n    at defaultResolve (node:internal/modules/esm/resolve:1173:11)\n    at nextResolve (node:internal/modules/esm/loader:173:28)\n    at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)\n    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)\n    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)\n    at link (node:internal/modules/esm/module_job:75:36) {\n  code: 'ERR_MODULE_NOT_FOUND'\n}\n\nNode.js v18.7.0\n"
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.62.1 (a748cf5a3 2022-06-08)`
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.15.0`
  - OK: **node**: `v18.7.0`
  - OK: **python3**: `Python 3.9.7`
  - OK: **pip3**: `pip 22.0.4 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **javac**: `javac 17.0.2`
  - OK: **java**: `openjdk version "17.0.2" 2022-01-18`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: Mon Aug 22 19:24:55 2022.
```

**Comment by williamboman** [comment]
Hello! Try updating the server, it should be fixed in their latest release (1.1.1)

**Comment by mslalith** [comment]
that resolved my issue, thanks @williamboman

**Comment by mslalith** [comment]
is there any way to notify the server updates?

**Comment by williamboman** [comment]
To check for new versions for all packages (also done by default when opening the window), press `C`. To check a single package, hover it and press `c`. For fully automatic upgrades, check https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim

https://asciinema.org/a/7VIdUK9fDNMG111bum5XtdWUq
