### ISSUE TITLE
Omnisharp does't work on Windows

### ISSUE THREAD

**Issue by Anakael** [williamboman/mason-lspconfig.nvim#38]
### Problem description

Omnisharp server doesn't work on Windows. Omnisharp itself works fine (via another plugin). 
On linux omnisharp works fine with mason lspconfig and starts with another command.

Also: 
1) mason-lspconfig don't allow to override cmd in lspconfig
2) mason-lspconfig don't configure root_dir correctly (but root_dir can be overrid manually in lspconfig)

### Why do you think this is an issue with mason-lspconfig.nvim?

Because it works fine if disable mason-lspconfig and configure lsp cmd manually.
Configuring root_dir also not required without mason-lspconfig and works fine.

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+26-gdb851cb10
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az158-777

### Operating system/version

Windows 10

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

Omnisharp

### Steps to reproduce

1) Open .cs file under solution.
See root_dir error in :LspInfo
2) Specify root_dir in lspconfig manualy (like cwd)
See no attached servers in :LspInfo

### Actual behavior

Omnisharp lsp doesnt't work. no --languageserver, --hostPID and (and maybe some others omnisharp options) options in cmd

### Expected behavior

Omnisharp lsp works fine. --languageserver and --hostPID (and maybe some others omnisharp options) in cmd

### LspInfo

```Text
Language client log: C:\Users\SHCHEM~1.DMI\AppData\Local\Temp\nvim\lsp.log
 Detected filetype:   cs
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: cs
 
 Config: omnisharp
 	filetypes:         cs, vb
 	root directory:    <WORKDIR_WITH_SOLUTION> (if specified via lspconfig)
 	cmd:               C:\Users\<NAME>\AppData\Local\nvim-data\mason\bin\omnisharp.CMD -s <SOLUTION_PATH>
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: omnisharp_mono, omnisharp, sumneko_lua
```

### LspLog

```Text
Starting RPC client with only -s option
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: unsupported version `go version go1.16.7 windows/amd64`. Go version must be >= 1.17.
  - WARNING: **cargo**: unsupported version `cargo 1.56.0 (4ed5d137b 2021-10-04)`. Some cargo installations require Rust >= 1.60.0.
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `6.14.5`
  - OK: **node**: `v16.1.0
`
  - OK: **python3**: `Python 3.9.6
`
  - OK: **pip3**: `pip 21.1.3 from C:\Users\shchemel.dmitry\AppData\Local\Programs\Python\Python39\lib\site-packages\pip (python 3.9)

`
  - OK: **javac**: `javac 16
`
  - OK: **java**: `java version "16" 2021-03-16
`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.11.4
`
  - OK: **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
  - ERROR: **gzip**: not available
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
  - OK: **python**: `Ok`
  - OK: **pip**: `pip 21.1.3 from C:\Users\shchemel.dmitry\AppData\Local\Programs\Python\Python39\lib\site-packages\pip (python 3.9)

`
  - OK: **JAVA_HOME**: `openjdk version "11.0.9" 2020-10-20 LTS
`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 8/30/2022 1:00:56 AM.
```

**Comment by williamboman** [comment]
Hello! I'm afraid `<WORKDIR_WITH_SOLUTION>` and `Starting RPC client with only -s option` omits the most useful information. 

> mason-lspconfig don't allow to override cmd in lspconfig

This has been an issue for quite some time, I went ahead and opened https://github.com/neovim/nvim-lspconfig/pull/2114 now which will allow for a more sensible approach.

> mason-lspconfig don't configure root_dir correctly (but root_dir can be overrid manually in lspconfig)

mason-lspconfig doesn't set a root_dir for Omnisharp, it'll default to lspconfig's root_dir definition for omnisharp

**Comment by Anakael** [comment]
-> `<WORKDIR_WITH_SOLUTION> ` and `Starting RPC client with only -s option` omits the most useful information.
Which additional information will be helpful?
Without setting work dir manually it just says that it can not be determined.

-> mason-lspconfig doesn't set a root_dir for Omnisharp, it'll default to lspconfig's root_dir definition for omnisharp
It used to work fine with `lsp_installer+lspconfig` for omnisharp and now works with other lsp installed throug mason. Was there any overrides for this in `lsp_installer`?

**Comment by Anakael** [comment]
I'll try to test it soon.

**Comment by Anakael** [comment]
Yes, now it works. Thank you!
