### ISSUE TITLE
client 1 quit with code 127 and 0 signal

### ISSUE THREAD

**Issue by fe2-Nyxar** [williamboman/mason-lspconfig.nvim#419]
### Problem description

![Screenshot_20240526_163644](https://github.com/williamboman/mason-lspconfig.nvim/assets/153492661/3a67797d-2459-42ea-bc11-9ef7a4b8db69)

```lua
local lsp = require("lsp-zero")

require('mason').setup({})
require('mason-lspconfig').setup({
    ensure_installed = {
        "lua_ls"
        --[["eslint",
        "tsserver",
        "bashls",
        "intelephense",
        "sqls",
        "cssls",
        "cssmodules_ls",
        "css_variables",--]]
        --"nil_ls"
    },
})


local lspconfig = require("lspconfig")
lspconfig.lua_ls.setup({}) ```

and i got an error : 
```client 1 quit with code 127 and 0 signal```

:LspLog's results
``` 
[start][date] LSP logging initiated
[Error][date] ../vim/lsp/rcp.lua "rcp"  "/home/.../.local/share/nvim/mason/bin/lua-language-server   stderr  "/home/.../.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server"  stderr   "/home/.../.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server/libexec/bin/lua-language-server" cannot execute: required file not found \n ```

### Why do you think this is an issue with mason-lspconfig.nvim?

it looks like it's trying to look for some executables but it can't find for some reason

### Neovim version (>= 0.7)

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/.../share/nvim
"

### Operating system/version

Linux nixos 6.1.91

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

lua_lsp for now

### Steps to reproduce

1- install lazy.vim 
2- install lsp-zero and all other packages with it
3- copy and paste what i have wrote

### Actual behavior

It doesn't work, no autocompletion or anything like that

### Expected behavior

it should work :)

### LspInfo

```Text
i don't know how to copy outside neovim
```

### LspLog

```Text
[START][2024-05-26 21:11:24] LSP logging initiated
[ERROR][2024-05-26 21:11:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/nyxar/.local/share/nvim/mason/bin/lua-language-server"	"stderr"	"/home/nyxar/.local/share/nvim/mason/bin/lua-language-server: line 3: /home/nyxar/.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server: cannot execute: required file not found\n"
[ERROR][2024-05-26 21:11:33] .../vim/lsp/rpc.lua:734	"rpc"	"/home/nyxar/.local/share/nvim/mason/bin/lua-language-server"	"stderr"	"/home/nyxar/.local/share/nvim/mason/bin/lua-language-server: line 3: /home/nyxar/.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server: cannot execute: required file not found\n"
[ERROR][2024-05-26 21:11:50] .../vim/lsp/rpc.lua:734	"rpc"	"/home/nyxar/.local/share/nvim/mason/bin/lua-language-server"	"stderr"	"/home/nyxar/.local/share/nvim/mason/bin/lua-language-server: line 3: /home/nyxar/.local/share/nvim/mason/packages/lua-language-server/libexec/bin/lua-language-server: cannot execute: required file not found\n"
```

### Healthcheck

```Text
i don't know how to copy outside neovim
```

**Comment by Solver42** [comment]
I get the same thing but only on windows
