### ISSUE TITLE
Feature: API to return server info

### ISSUE THREAD

**Issue by ray-x** [williamboman/mason-lspconfig.nvim#44]
### Is your feature request related to a problem? Please describe.

As mason does not install the lsp binary in PATH, it is had to tell where those binaries are installed.
given, I need to check tsserver install info
I invoke a api, e.g. require('mason_lspconfig').get_install_path('python-lsp-server')
want: I got a table of
```
{
  installed: true,
  root_path:'/home/user/.local/share/nvim/mason/packages/python-lsp-server/'
  bin_path: '/home/user/.local/share/nvim/mason/packages/python-lsp-server/venv/bin/python-lsp-server'
  version: '1.1.1'
}
```
Or maybe a lsp info style of info:

```
{
  installed: true,
  cmd = { "/home/user/.local/share/nvim/mason/packages/pyright/pyright-langserver", "--stdio" },
  version: '1.1.1`
}
```

The limitation of  `pkg:get_install_path()` is that it only include a root path, pylsp was install in a sub folder `venv/bin` in above case.

### Describe the solution you'd like

Add a new API to query server install info.

### Describe potential alternatives you've considered

Alternatively
Add:
 require('mason_lspconfig').pylsp.setup({})
and 
 require('mason_lspconfig').pylsp.default_setup()
The  `require('mason_lspconfig').pylsp`.default_setup will return a default setup that are used by mason.

**Comment by williamboman** [comment]
Hello!

> As mason does not install the lsp binary in PATH, it is had to tell where those binaries are installed.

Hm it seems like you might've misunderstood something. Mason will link executables to a single location (by default `~/.local/share/nvim/mason/bin` on *NIX and `~\AppData\local\nvim-data\mason\bin` on Windows). Here's for example how by bin directory looks like:

```
$ ls --color=never -lA ~/.local/share/nvim/mason/bin/ | head -n 10
total 0
lrwxr-xr-x 1 williamboman staff 33 Aug 31 02:06 actionlint -> ../packages/actionlint/actionlint
lrwxr-xr-x 1 williamboman staff 71 Aug 19 15:10 bash-language-server -> ../packages/bash-language-server/node_modules/.bin/bash-language-server
lrwxr-xr-x 1 williamboman staff 49 Aug 31 13:08 cbfmt -> ../packages/cbfmt/cbfmt_macos-x86_64_v0.2.0/cbfmt
lrwxr-xr-x 1 williamboman staff 36 Aug 29 15:16 clangd -> ../packages/clangd/clangd/bin/clangd
lrwxr-xr-x 1 williamboman staff 29 Sep  3 01:31 codelldb -> ../packages/codelldb/codelldb
lrwxr-xr-x 1 williamboman staff 40 Aug 18 23:14 codespell -> ../packages/codespell/venv/bin/codespell
lrwxr-xr-x 1 williamboman staff 27 Aug 19 17:39 debugpy -> ../packages/debugpy/debugpy
lrwxr-xr-x 1 williamboman staff 35 Aug 19 17:39 debugpy-adapter -> ../packages/debugpy/debugpy-adapter
lrwxr-xr-x 1 williamboman staff 74 Aug  6 19:05 docker-langserver -> ../packages/dockerfile-language-server/node_modules/.bin/docker-langserver
```

When calling `require("mason").setup()`, this directory is prepended to the `PATH` environment of the running Neovim instance. This makes it possible to refer to these executables by their canonical name - absolute paths to executables should really never be needed with Mason.

---

Generally, mason-lspconfig itself doesn't concern itself with which executable(s) an LSP server uses. This is governed by the server configurations in lspconfig. There are a [few exceptions](https://github.com/williamboman/mason-lspconfig.nvim/tree/main/lua/mason-lspconfig/server_configurations) that handle situations where for example `lspconfig` doesn't provide a cmd. If you for whatever reason want to access the `cmd` a server use, you should do that via lspconfig, for example `require("lspconfig.server_configurations.pylsp").default_config.cmd`.

**Comment by williamboman** [comment]
I saw the linked issue. What they should've done is simply

```lua
require("lspconfig").setup {}
```

It seems like navigator.lua exposes a wrapper API for setting up LSP servers, is there a specific need for that?

**Comment by ray-x** [comment]
Thanks, If those binaries are linked in $data/mason/bin/ it is convenient.
The reason for navigator wrap-up lsp setup is
1) provide a way to simplify the lsp setups.
2) dynamically lazy load lsp based on file type and user config.
