### ISSUE TITLE
Dart language server?

### ISSUE THREAD

**Issue by marroen** [williamboman/mason-lspconfig.nvim#46]
### Is your feature request related to a problem? Please describe.

I would love to use mason.nvim for integrating my LspConfig with all languages I regularly use, and thus I would love a Dart language server.

### Describe the solution you'd like

Linking it to mason-lspconfig.nvim

**Comment by williamboman** [comment]
Hello! Dart bundles their LSP server with the runtime executable itself. My rationale for not including Dart in Mason is that if you're developing for Dart you ought to have the runtime installed on your system already (i.e. managed outside of Mason). I'd like to explore runtime & compiler management in Mason in the future, but for that to be useful I think project-local or multi-version installations need to be supported first.

**Comment by williamboman** [comment]
So to use the Dart LSP you can just so

```
lspconfig.dart.setup {}
```

**Comment by 3nt3** [comment]
this sadly doesn't seem to work for me (although I've never configured my nvim using lua before so the error's probably on my side):

```lua
require('lspconfig').dart.setup {}
```

**Comment by ALipAkrohk** [comment]
Hello, I have this problem too, lsp is not recognized for Dart language and this is a problem that needs to be fixed.
I first progressed with your method but didn't get an answer, so I tried to go through the nvim-lspconfig documents, but mason can't find dartls.

![image](https://user-images.githubusercontent.com/27810360/213921364-77df535e-21b7-4cbe-b957-6d2d5dc2aed8.png)
![image](https://user-images.githubusercontent.com/27810360/213921422-88238c46-f092-4b93-8919-86ca968f410c.png)
![image](https://user-images.githubusercontent.com/27810360/213921445-9393ebef-bb0d-4fa5-88b4-7d21b0b1f4cd.png)

https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#dartls

**Comment by williamboman** [comment]
@ALipAkrohk Mason doesn’t provide installation for Dart, for reasons mentioned in my comment above.

**Comment by jjeejj** [comment]
dart Language Server Protocol  https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec

**Comment by nyngwang** [comment]
@jjeejj Did you mean that we should use [Using LSP with Dart-Vim](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec#using-the-dart-lsp-server-in-editors) in your linked documentation for the hints about how to set it up?

**Comment by jjeejj** [comment]
> @jjeejj Did you mean that we should use [Using LSP with Dart-Vim](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec?rgh-link-date=2023-04-22T15%3A30%3A01Z#using-the-dart-lsp-server-in-editors) in your linked documentation for the hints about how to set it up?

Directly use lspconfig

```lua
require("lspconfig").dartls.setup({
            cmd = { "dart", "language-server", "--protocol=lsp" },
            filetypes = { "dart" },
            init_options = {
                closingLabels = true,
                flutterOutline = true,
                onlyAnalyzeProjectsWithOpenFiles = true,
                outline = true,
                suggestFromUnimportedLibraries = true,
            },
            -- root_dir = root_pattern("pubspec.yaml"),
            settings = {
                dart = {
                    completeFunctionCalls = true,
                    showTodos = true,
                },
            },
            on_attach = function(client, bufnr)
				...
            end,
        })
```

**Comment by GiorgosXou** [comment]
Am I the the only one who experiences **extremely sluggish behavior** while using lsp inside Neovim?
