### ISSUE TITLE
Better feedback when installing a server

### ISSUE THREAD

**Issue by dave-kennedy** [williamboman/mason-lspconfig.nvim#48]
### Is your feature request related to a problem? Please describe.

I added `require('lspconfig').pylsp.setup({})` to my configuration and opened a Python file in Neovim. However, because there was no indication that anything was happening, I closed Neovim before it had a chance to finish installing. This put me into a weird state until I cleared the .local/share/nvim/mason directory. So it would be cool if the UI showed something.

Similarly, I added `require('lspconfig').metals.setup({})` and waited around for a while to see if anything happened nothing ever did. I assume because this plugin doesn't recognize "metals" it didn't even try. It would be nice if the UI showed something in this case too.

### Describe the solution you'd like

Show a message when something is downloading/installing.

Show a message when something fails to install or is unsupported.

**Comment by williamboman** [comment]
Hello! Ah I thought messages were presented already. Hopefully #51 improves this, otherwise PRs are welcome!

**Comment by chancez** [comment]
When I open Neovim, as far as I can tell, there's no message or notification about any installations occurring that I can see.

**Comment by chancez** [comment]
Ah it's only logging in the case of `automatic_installation`, not when using `ensure_installed`, that's why.

**Comment by williamboman** [comment]
> Ah it's only logging in the case of `automatic_installation`, not when using `ensure_installed`, that's why.

Added in #91!
