### ISSUE TITLE
Failure to detect PHP and Composer on Void Linux

### ISSUE THREAD

**Issue by the-lazy-learner** [williamboman/mason-lspconfig.nvim#52]
This question may come as being distribution specific but the packages for Void Linux have binaries named as php8.1 and composer8.1 respectively which is probably why mason is unable to detect them. I thought maybe trying to create aliases might work but it didn't seem to work. Any idea how I could get intelephense or some other php language server to work properly on my environment?

Thank you!

**Comment by williamboman** [comment]
You'll have to ensure `php` and `composer` is in your PATH. Symlinking `php -> php8.1` is probably the most straightforward method

**Comment by the-lazy-learner** [comment]
It seems to detect them now but no LSP completion seems to appear
