### ISSUE TITLE
awk-language-server ERR_INVALID_URL

### ISSUE THREAD

**Issue by CharlesARoy** [williamboman/mason-lspconfig.nvim#59]
### Problem description

When I load an awk file, I get the generic error `Client 1 quit with exit code 1 and signal 0` indicating that the language server failed to launch. 

### Why do you think this is an issue with mason-lspconfig.nvim?

When I review the LspLogs, the error appears to be a parsing problem for a file that was obtained with the awk-language-server downloaded via Mason.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by croy@node1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/data/usr/croy/.linuxbrew/Cellar/neovim/0.7.2_1/share/nvim"

### Operating system/version

Linux node1 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

awk-language-server (awk_ls)

### Steps to reproduce

This is difficult to summarize as I have 20+ plugins installed. Most of my configuration is quite standard/basic.

My config isn't public but it is heavily based on Christian Chiarulli's, which can be seen [here](https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/lsp/mason.lua).

Relative to the above file, I added "awk_ls" to the servers and `require'lspconfig'.awk_ls.setup{}` at the bottom.

### Actual behavior

Upon launching a .awk file, the language server fails to load. 

### Expected behavior

I expected the awk-language-server to start normally.

### LspInfo

```Text

After the language server fails to load, when I run :LspInfo, I get the following errors in the console. (Note that LspInfo works normally in other files).


E5108: Error executing lua ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:56: attempt to call field 'get_root_dir' (a nil value)
stack traceback:
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:56: in function 'make_config_info'
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:214: in function <...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:142>
        .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:19: in function <.../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:18>
        [string ":lua"]:1: in main chunk
```

### LspLog

```Text

Yes, the relevant error seems to be:

Failed to parse URL from /data/usr/croy/.local/share/nvim/mason/packages/awk-language-server/node_modules/awk-language-server/node_modules/web-tree-sitter/tree-sitter.wasm\n

I can paste the full error message if helpful.
```

### Healthcheck

```Text
See screenshot.
```

### Screenshots or recordings

![image](https://user-images.githubusercontent.com/46253001/190033942-bfa2ffd6-dd56-42e5-a26c-7fee7aaa8def.png)

**Comment by williamboman** [comment]
Hello! This is most likely an issue with the package itself, I found https://github.com/Beaglefoot/awk-language-server/issues/33 which suggests using Node v16. I'll open a PR to lspconfig to fix the issue you're having with `:LspInfo` though
