### ISSUE TITLE
please support gradle language server installation

### ISSUE THREAD

**Issue by rajcspsg** [williamboman/mason-lspconfig.nvim#60]
### Is your feature request related to a problem? Please describe.

currently `:MasonInstall` doesn't list gradle_ls.

### Describe the solution you'd like

would like to get support for easy installation of gradle_ls using mason

### Describe potential alternatives you've considered

installing gradle_ls manually is overwhelming and cumbersome and it doesn't work for me as well.

### Additional context

please see here for more details https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#gradle_ls

**Comment by williamboman** [comment]
https://github.com/williamboman/mason.nvim/issues/422
