### ISSUE TITLE
`Setup_handlers` before `setup` would cause lsps not attached on windows

### ISSUE THREAD

**Issue by TisnKu** [williamboman/mason-lspconfig.nvim#78]
Hi there, thanks for the amazing plugin. Recently, I came across a weird bug that on windows my rust and taplo lsp cannot attach to buffer, but other lsps like `tsserver` and `jsonls` works normally! After some debugging I found the root cause is the order of setup calls. Curious why this happens and is it possible to make the behavior consistent?

# For `rust-analyzer` & `taplo` , this does not work on Windows, but works on Mac
```
require('mason').setup {}
require('mason-lspconfig').setup_handlers {
  function(server_name)
    require('lspconfig')[server_name].setup {}
  end
}
require('mason-lspconfig').setup {}
```
# This works both on Windows and Mac
```
require('mason').setup {}
require('mason-lspconfig').setup {}
require('mason-lspconfig').setup_handlers {
  function(server_name)
    require('lspconfig')[server_name].setup {}
  end
}
```

**Comment by TisnKu** [comment]
BTW, my nvim version on windows: 
```
NVIM v0.9.0-dev-47-gcfdb4cbad
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az555-59
```

**Comment by williamboman** [comment]
Hey! You need to call `.setup()` before `.setup_handlers()`
