### ISSUE TITLE
automatic_installl doesnt automatically install

### ISSUE THREAD

**Issue by dagadbm** [williamboman/mason-lspconfig.nvim#8]
### Problem description

I have the following setup (check screenshot)

But the language servers did not get automatically installed. They first had to fail when I opened a project with those languages and only afterwards did they install. Which is not the same behavior you had before from nvim-lsp-installer.

This plugin also confuses me a little bit because now you also have the mason-tool-installer but I'm not sure I should be using that one for the lsps right? probably only for the linters and so on.

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-nightly-84-g7961f7990
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin ip-192-168-1-100.ec2.internal 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110 arm64

### I've recently downloaded the latest plugin version of mason.nvim & mason-lspconfig.nvim

- [X] Yes

### Affected packages

all

### Actual behavior

mason-lspconfig is not installing LSPs automatically

### Expected behavior

He should install them automatically even if you are not in the filetype

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.4 darwin/arm64`
  - OK: **cargo**: `cargo 1.62.1 (a748cf5a3 2022-06-08)`
  - OK: **luarocks**: `/opt/homebrew/bin/luarocks 3.9.1`
  - OK: **Ruby**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`
  - OK: **RubyGem**: `3.3.7`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.13.2`
  - OK: **node**: `v18.6.0`
  - OK: **python3**: `Python 3.10.5`
  - OK: **pip3**: `pip 22.0.4 from /Users/dagadbm/.asdf/installs/python/3.10.5/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: Tue Jul 26 01:13:39 2022.
```

### Screenshots

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/16737095/180890111-c5d761cc-be53-4a25-9284-de8248d315d0.png">

**Comment by WhoIsSethDaniel** [comment]
@dagadbm you can use mason-tool-installer for lsp, linters, anything that mason can install. FWIW I wrote mason-tool-installer because I needed, ASAP, a way to have many different hosts to have the same third-party tools installed for neovim (and I don't have ultimate control over these hosts). 

I'm sorry I can't help you with your actual problem.

**Comment by williamboman** [comment]
> This plugin also confuses me a little bit because now you also have the mason-tool-installer but I'm not sure I should be using that one for the lsps right? probably only for the linters and so on.

Just to clarify: mason-tool-installer is entirely a 3rd party plugin, I've not been involved in that at all. It provides a way to automatically ensure the provided packages are installed (this will [eventually be supported](https://github.com/williamboman/mason.nvim/issues/103) in core). It seems like you're passing an empty table to its setup function, I'd reread their README to see what you need to provide.

I can't see the full setup code in the screenshot, but what the `automatic_installation` setting does is to automatically install servers that you set up via `lspconfig`:

```lua
require("mason").setup()
require("mason-lspconfig").setup {
  automatic_installation = true
}

lspconfig.sumneko_lua.setup {} -- by calling lspconfig's setup function, sumneko_lua will be installed if it's not already
lspconfig.pylsp.setup {} -- same
...
```

**Comment by dagadbm** [comment]
maybe what happens is if I change directory with one where asdf-direnv is available he doesnt check if the language servers are installed?

because i have different projects that use different node version etc so just because you npm install -g something doesnt mean it will always be there if you go to another folder.

Either way I can now share my config (i had to push the code):

https://github.com/dagadbm/dotfiles/blob/master/nvim/dotfiles/plugins.lua#L98
this is the lps plugins I am using.

And this is the setup that I have for the lsp stuff:
https://github.com/dagadbm/dotfiles/blob/master/nvim/dotfiles/lsp.lua

Also the auto installer package will not work (I think) If I have a custom setup for the lsp servers right?
For example lua-dev and typescript.nvim (this package I cant even lspconfig.setup the server because it does it by himself)

**Comment by junnplus** [comment]
@dagadbm Hi, I looked at your `lsp.lua` file, and found it to be very similar to the plugin I did -- [nvim-lsp-setup](https://github.com/junnplus/nvim-lsp-setup), it can save you from tedious configuration.

The master branch use nvim-lsp-installer for install lsp server, it also support mason-lspconfig, you can see https://github.com/junnplus/nvim-lsp-setup/pull/21

**Comment by dagadbm** [comment]
i actually adapted it from your code!
I have to thank you because yours was the simplest solution I could find and it is what helped wrap my head around lsp! 

thank you :D 

I will check your PR.

This community moves so fast you can't keep up with everything :D

**Comment by dagadbm** [comment]
so it seems this is the magic: `require('mason-core.package').Parse(server)` ?
Btw does this allow passing custom serve configs like for lua-dev?

Things are still a bit confusing in my head tbh. Too many moving parts.

I'm also curious how this whole thing will work will dap and null-ls (or if you even need them if you go full on mason).

But I do think mason with be the "new coc" for neovim thats why I sponsored the creator as well.

Either way I'm curious how this holds with asdf-direnv and its a shame not many developers use it because its super power-full.

**Comment by junnplus** [comment]
> so it seems this is the magic: `require('mason-core.package').Parse(server)` ?

It supports service with version, like `rust_analyzer@nightly`.

> Btw does this allow passing custom serve configs like for lua-dev?

`nvim-lsp-setup` can be integrated with `lua-dev`: https://github.com/junnplus/nvim-lsp-setup#lua-dev

**Comment by williamboman** [comment]
> maybe what happens is if I change directory with one where asdf-direnv is available he doesnt check if the language servers are installed?
> 
> because i have different projects that use different node version etc so just because you npm install -g something doesnt mean it will always be there if you go to another folder.

Ah, no. Mason avoids this problem by installing to its own location. It'll simply run the provided tools using whatever runtime that happens to be active in your Neovim session (most likely this will be inherited from the shell in which it was started in). This however comes with a few other drawbacks, and I'd like to be able to pin runtimes to be used (see https://github.com/williamboman/mason.nvim/issues/166).

> Also the auto installer package will not work (I think) If I have a custom setup for the lsp servers right?

The automatic installation will be triggered for all servers that are set up via lspconfig. I believe both typescript.nvim and lua-dev uses lspconfig behind the scenes, so those plugins will indeed trigger automatic installations.

> I'm also curious how this whole thing will work will dap and null-ls (or if you even need them if you go full on mason).

Mason only installs external tooling for you, it doesn't do anything to integrate these into the editor. Formatters are probably the only tool that can easily be used solely with builtin mechanisms (e.g. `:%!prettier --write %`) - other tooling will need 3rd party plugins for a richer integration. This particular plugin (`mason-lspconfig`) aims to bridge `mason` with the `lspconfig` plugin, for a smooth LSP experience. I do see a need for similar plugins for other use cases, for example `mason-dap` for `nvim-dap` integration and `mason-null-ls` for `null-ls`, etc.

**Comment by williamboman** [comment]
@dagadbm Did you manage to resolve your issue, can we close this? The `automatic_installation` should work fine (again the requirement is for the `lspconfig[server_name].setup()` function to be called).

**Comment by dagadbm** [comment]
yes you can close it!

Thanks for all the answers and you are the first person I evern sponsored on github :)

**Comment by baco** [comment]
How did you achieve it? I am having the same issue, I have in my configs:

```lua
require("mason-lspconfig").setup({ automatic_installation = true })
require"lspconfig".pyright.setup{}
```

but when I open a `.py` file, mason doesn't download Pyright at all and I get the following error message:

```
Spawning language server with cmd: `pyright-langserver` failed. The language server is either not installed, missing from PATH, or not executable.
```

**Comment by russsaidwords** [comment]
@baco You have the ordering swapped. Run the lspconfig setup first, then the mason-lspconfig setup with the automatic installation. You might have to open and close Neovim once to get everything installed automatically; you can check installation status with ":Mason".

**Comment by williamboman** [comment]
Mason needs to be set up before lspconfig!
