### ISSUE TITLE
Add support for `cl-lsp`

### ISSUE THREAD

**Issue by kylechui** [williamboman/mason-lspconfig.nvim#86]
### Is your feature request related to a problem? Please describe.

As of right now, there is language server support for lispy languages like Clojure, but there doesn't seem to be any support for common lisp.

### Describe the solution you'd like

It would be nice to have a language server for common lisp, i.e. [cl-lsp](https://github.com/cxxxr/cl-lsp).

### Additional context

Pardon my ignorance, but I'm unsure if [this issue](https://github.com/neovim/nvim-lspconfig/issues/1767) is relevant at all, i.e. is this something that would need to be implemented upstream first?

**Comment by williamboman** [comment]
Superseded by https://github.com/williamboman/mason.nvim/issues/662

> Pardon my ignorance, but I'm unsure if [this issue](https://github.com/neovim/nvim-lspconfig/issues/1767) is relevant at all, i.e. is this something that would need to be implemented upstream first?

For it to be added in mason-lspconfig, yes it'd need to be added to nvim-lspconfig first.
