### ISSUE TITLE
Can't install any of the ruby LSPs.

### ISSUE THREAD

**Issue by MetuMortis-code** [williamboman/mason-lspconfig.nvim#94]
### Problem description

Can't install any of the ruby LSPs.
![Screenshot_20221104_220143](https://user-images.githubusercontent.com/78408599/200056454-540573c3-8af6-4ae3-ba49-d7d4ed62d731.png)

### Why do you think this is an issue with mason-lspconfig.nvim?

It throws "Cannot link Gem executable "ruby-lsp" because it doesn't exist in "bin/ruby-lsp"." error.

### Neovim version (>= 0.7)

NVIM v0.8.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/build/cmake.config -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/src -I/usr/include -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.8.0/build/include
Compiled by abuild@OBS

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux metumortis-monster 5.19.13-1-default #1 SMP PREEMPT_DYNAMIC Wed Oct 5 09:13:41 UTC 2022 (7df3755) x86_64 x86_64 x86_64 GNU/Linux

### I've manually reviewed the Nvim LPS client log (`:LspLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim, mason-lspconfig.nvim, and nvim-lspconfig

- [X] Yes

### Affected language servers

ruby-lsp solargraph sorbet

### Steps to reproduce

1. Open a Linux machine
2. Install NVIM and install mason plugin
3. Try installing specified plugins.

### Actual behavior

It doesn't install them.

### Expected behavior

It should install them.

### LspInfo

```Text
-
```

### LspLog

```Text
[START][2022-11-04 22:08:21] LSP logging initiated
[WARN][2022-11-04 22:08:21] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-11-04 22:08:21] .../lua/vim/lsp.l
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.1 linux/amd64`
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]`
  - OK: **RubyGem**: `3.3.7`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v18.9.0`
  - OK: **python3**: `Python 3.10.7`
  - OK: **pip3**: `pip 22.0.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 18.0.2`
  - OK: **java**: `openjdk version "18.0.2" 2022-07-19`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.85.0 (x86_64-suse-linux-gnu) libcurl/7.85.0 OpenSSL/1.1.1q-fips zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.50.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-suse-linux)`
  - OK: **sh**: `Ok`
  - OK: **JAVA_HOME**: `openjdk version "18.0.2" 2022-07-19`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Cum 04 Kas 2022 23:15:42.
```

**Comment by williamboman** [comment]
Hello! Could you try installing again with :MasonInstall --debug solargraph. Assuming the installation still fails, could you go to the directory printed at the very end of the installation log output and check the contents of it?

```
$ cd <path>
$ ls -l
$ ls -l bin/
```

**Comment by MetuMortis-code** [comment]
![Screenshot_20221106_112937](https://user-images.githubusercontent.com/78408599/200161367-0db667ca-9c52-4671-ae6b-6efdb2316bf8.png)
![Screenshot_20221106_112918](https://user-images.githubusercontent.com/78408599/200161369-dcc7bcdc-93c1-4b77-9006-e7eae183b0c4.png)

**Comment by williamboman** [comment]
Should hopefully be fixed if you pull the latest mason.nvim version!

**Comment by MetuMortis-code** [comment]
> Should hopefully be fixed if you pull the latest mason.nvim version!

Yes thanks.

**Comment by vkuppoor** [comment]
Hey, I'm experiencing the same issue again. I'm using the up to date version of Mason, but I can't install any of the Ruby LSPs like solargraph. I posted below an image of what's in the directory produced by the :MasonInstall --debug solargraph command.
[mason-solargraph-issue.pdf](https://github.com/williamboman/mason-lspconfig.nvim/files/10775379/mason-solargraph-issue.pdf)
![Image 2-18-23 at 6 26 PM](https://user-images.githubusercontent.com/49379423/219904227-d67921cc-59d2-469a-9ac5-e4d595d6616d.jpg)
