### ISSUE TITLE
Add ccls support

### ISSUE THREAD

**Issue by Ae-Mc** [williamboman/mason-lspconfig.nvim#97]
### Is your feature request related to a problem? Please describe.

There is no alternative to very limited clangd that couldn't be completely configured via lsp arguments.

### Describe the solution you'd like

Add support of [ccls](https://github.com/MaskRay/ccls) lsp server.

**Comment by williamboman** [comment]
Hello! ccls is not supported due to complexities in building it across platforms. I'd recommend installing it via your system's package manager or building it yourself!
