### ISSUE TITLE
Automatic installation Isn't installing servers.

### ISSUE THREAD

**Issue by jzone1366** [williamboman/mason-lspconfig.nvim#98]
So I currently have Mason setup to have the UI.
I use this package with the `automatic_installation` flag to true and use nvim-lspconfig to configuring my servers. 
The above set up in the past has automatically installed the servers and I'm currently getting the notifications that pop up and say `mason.nvim  INFO [mason-lspconfig.nvim] automatically installing bash-language-server` 

But to no avail nothing ever gets installed. I can run the servers that I'm installing via `MasonInstall <name>` and they Install fine.

Is there anything I'm missing now?

Thanks!

**Comment by williamboman** [comment]
Few more questions:
- do you launch multiple neovim instances simultaneously?
- do you let the installation finish before exiting neovim?

Could you provide the Mason logs as well (set log level to `DEBUG` first - `:h mason-debugging`)?

```vim 
" 1. Uninstall any packages that should be auto installed
:MasonUninstall bash-language-server

" 2. Truncate the log file first
:MasonLog
:%d
:w
```

Then restart Neovim and let the installation finish, then please provide the contents of `:MasonLog`.

**Comment by jzone1366** [comment]
> 

I have set the log level to Debug and there is nothing in the log at all. I still get the notifications in notify but nothing else happens. I've been removing packages from my config but to no avail still not auto downloading.

**Comment by jzone1366** [comment]
> do you perhaps have a minimal config for reproducing this?

I don't yet. I've been trying to find a minimal config that I can reproduce and I seem to be getting it all the time. I have my nvim config [here](https://gitlab.com/jzone1366/dots/-/tree/main/nvim) if you would like to take a look

**Comment by jzone1366** [comment]
Figured out that it doesn't play well with nvim-notify if I use `vim.notify = notify` in my config. Once I remove that it had no issues installing. Trying to figure out why exactly.

**Comment by jzone1366** [comment]
NVM. This has nothing to do with anything here. It's an issue with lazy loading and events.

**Comment by tusharsnn** [comment]
I having the same issues, @jzone1366 Can you share how you fixed it? I am using lazy.nvim for plugin management.
